[project]
name = "server-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Victor-MT", email = "victor.martins1699@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "flask-cors>=6.0.5",
    "optimum>=2.3.0",
    "scipy>=1.18.1",
    "transformers>=5.17.0",
]

[project.scripts]
server-python = "server_python:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
